<a href="https://colab.research.google.com/github/MichaelTotaro/github.io/blob/master/Summer_2025_INFX_639_Ch_3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **Chapter 3: Deep Learning Libraries**

This chapter discusses the important libraries and frameworks that one needs to get started in artificial intelligence. We'll cover the basic functions of the three most popular deep learning frameworks: Tensorflow, Pytorch, and Keras, and show you how to get up and running in each of these frameworks as we will be utilizing them in the following chapters. A reminder that these deep learning frameworks are already pre-installed in Google Colab.

Finally, the chapter touches upon computing for Artificial Intelligence, and discusses how GPUs and other advanced memory units can improve AI.

In [ ]:
import numpy as np

### **TensorFlow Basics**

In [ ]:
import tensorflow as tf

In [ ]:
## Define two constants
x = tf.constant(2)
y = tf.constant(2)

## Multiply the constants
product = tf.multiply(x, y)

In [ ]:
# Define two constants
x = tf.constant(2)
y = tf.constant(2)

# Multiply the constants
product = tf.multiply(x, y)

# In TensorFlow 2.x, operations are executed eagerly,
# so we don't need to initialize variables or use sessions
print(product.numpy()) # Use .numpy() to get the value of the tensor

# No session to close in eager execution

4


Creating a new graph

In [ ]:
my_graph = tf.Graph()

with my_graph.as_default():
            x = tf.constant(2)
            y = tf.constant(2)

Scopes:

In [ ]:
with tf.name_scope("my_scope"):
            ## Define two constants
            const1 = tf.constant([4])
            const2 = tf.constant([5])

            ## Multiply the constants
            product = tf.multiply(const1, const2)

### **Keras Basics**

As Keras is designed as a model-level library, it does not contain methods for doing basic operations as PyTorch of base TensorFlow does. Instead, it utilizes TensorFlow as a backend. As such, its basic operations are the same as basic TensorFlow operations:

In [ ]:
import keras.backend as K

Using TensorFlow backend.

In [ ]:
import tensorflow as tf
import keras.backend as K # Keep this import if other Keras backend functions are used later

# Using tf.constant directly
x = tf.constant(5)
y = tf.constant(6)
product = x * y

# You can still print the result similar to how you did with TensorFlow basics
print(product.numpy())

30


### **PyTorch**

In [ ]:
import torch

In [ ]:
x = torch.IntTensor([4])
y = torch.IntTensor([5])
product = x * y

It's easy to switch between numpy and pytorch

In [ ]:
## Create a numpy array
numpy_array = np.random.randn(10,10)

##Convert the numpy array to a pytorch tesnor
pytorch_tensor = torch.from_numpy(numpy_array)

## Convert it back to Numpy
numpy_again = pytorch_tensor.numpy()

Pytorch tensors can be manipulated in a way that is similar to numpy

In [ ]:
tensor = torch.FloatTensor([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

## print the third element of the 2nd row of the tensor
print(tensor[1][2])

tensor(6.)


In [ ]:
## replace the second value of the first tensor
tensor[0][1] = 1
print(tensor)

tensor([[1., 1., 3.],
        [4., 5., 6.],
        [7., 8., 9.]])


Like TensorFlow, PyTorch runs on the concept of variables, which are values that are intended to change and be updated during training processes

In [ ]:
from torch.autograd import Variable

## Create a tensor
tensor_two = torch.tensor([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

## Convert it to a variable
variable = Variable(tensor_two)

In [ ]:
variable.data

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

### **TensorFlow Logging**

In [ ]:
import tensorflow as tf

my_list = []
## Iterate through the available GPUs
# Note: In a real environment, you would check if these devices are available.
# For demonstration, we'll assume they are or let TensorFlow handle device placement.
# In TensorFlow 2.x, device placement is often handled automatically.
# You can list available devices using tf.config.list_physical_devices()
available_devices = tf.config.list_physical_devices()
print("Available devices:", available_devices)


for device in ['/gpu:0', '/gpu:1']:
    ## Utilize the TensorFlow device manager
    try:
        with tf.device(device):
            x = tf.constant([1,2,3], shape=[1,3])
            # Fix: Add '=' after shape to make it a keyword argument
            y = tf.constant([1,2,3], shape=[3,1])
            # In TensorFlow 2.x, tf.matmul returns a tensor directly in eager execution
            matmul_result = tf.matmul(x, y)
            my_list.append(matmul_result)
            # Print the result of the matrix multiplication
            print(f"Matrix multiplication on {device}:")
            print(matmul_result.numpy())

    except tf.errors.InvalidArgumentError as e:
        # Catch errors if a device is not available
        print(f"Device {device} not available or operation failed: {e}")


with tf.device('/cpu:0'):
    # Note: tf.add requires shapes to be compatible for element-wise addition.
    # Adding a (1,3) tensor and a (3,1) tensor directly will result in a (3,3) tensor due to broadcasting.
    # This might not be the intended behavior if element-wise addition was expected.
    # If you want element-wise addition, shapes must match.
    # Example:
    # x_cpu = tf.constant([[1, 2, 3]])
    # y_cpu = tf.constant([[1, 2, 3]]) # y_cpu needs to have the same shape
    # sum_operation = tf.add(x_cpu, y_cpu)

    # Based on the original code structure, it seems you intended to add x and y.
    # TensorFlow 2.x broadcasting will handle this, resulting in a (3,3) tensor.
    sum_operation = tf.add(x, y)
    # Print the result of the addition
    print("\nAddition on /cpu:0:")
    print(sum_operation.numpy())


# Note: In TensorFlow 2.x eager execution, you don't need a session.
# Operations are executed immediately when they are called.
# The results are available directly as tensors.
# sess = tf.Session(config=tf.ConfigProto(log_device_placement=True)) # This line is removed
# sess.run(sum_operation) # This line is removed

# Access the results directly
# print(sum_operation.numpy()) # Already printed above
# print(my_list[-1].numpy()) # Access the last matrix multiplication result, already printed above

Available devices: [PhysicalDevice(name='/physical_device:CPU:0', device_type='CPU')]
Matrix multiplication on /gpu:0:
[[14]]
Matrix multiplication on /gpu:1:
[[14]]

Addition on /cpu:0:
[[2 3 4]
 [3 4 5]
 [4 5 6]]
